export const GARMENTS = ["Tee", "Sweatshirt", "Jeans"] as const;
export const SHOTS = ["Hanger", "Studio", "Flat lay", "On body"] as const;
export const LOOK_ASPECTS = ["portrait", "square"] as const;

export type Look = {
  id: number;
  name: string;
  garment: (typeof GARMENTS)[number];
  shot: (typeof SHOTS)[number];
  summary: string;
  /** Your locked Fal prompt. Users never see this. */
  prompt: string;
  /** Look reference photos. Numbered #2, #3… after the user mockup. */
  refs: string[];
  aspect: (typeof LOOK_ASPECTS)[number];
};

/**
 * Edit these in Settings while running locally. Save writes this file.
 */
/* looks:start */
export const LOOKS: Look[] = [
  {
    id: 1,
    name: "Distressed Graphic Tee",
    garment: "Tee",
    shot: "Hanger",
    summary: "Vintage cream tee, raw hem, punk collage print.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 2,
    name: "Oversized Graphic Sweatshirt",
    garment: "Sweatshirt",
    shot: "Studio",
    summary: "Boxy heather gray sweatshirt with a faded chest graphic.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 3,
    name: "Saint Distressed Tee",
    garment: "Tee",
    shot: "Studio",
    summary: "Cropped off-white tee, frayed edges, faded icon print.",
    prompt: `## PRIMARY OBJECTIVE

CREATE A **100% PHOTOREALISTIC, PROFESSIONAL E-COMMERCE PRODUCT MOCKUP** USING EXACTLY TWO REFERENCE IMAGES.

THE FINAL IMAGE MUST SHOW THE **EXACT CUSTOMER T-SHIRT FROM IMAGE #1** — INCLUDING ITS EXACT SHIRT COLOR, GRAPHICS, PRINTS, TEXT, LOGOS, ARTWORK, DESIGN DETAILS, AND VISUAL IDENTITY — BUT THE T-SHIRT MUST BE **PRESENTED, SHAPED, POSITIONED, AND PHOTOGRAPHED IN THE SAME MOCKUP STYLE AS IMAGE #2**.

THE SIMPLE RULE IS:

**IMAGE #1 = THE PRODUCT / DESIGN SOURCE.**
**IMAGE #2 = THE PRESENTATION / MOCKUP SOURCE.**

IMAGE #2 MUST NEVER OVERRIDE THE CUSTOMER'S ACTUAL PRODUCT DESIGN FROM IMAGE #1.

---

# IMAGE ASSIGNMENTS

## IMAGE #1 — ABSOLUTE PRODUCT DESIGN SOURCE

IMAGE #1 IS THE CUSTOMER'S ACTUAL T-SHIRT MOCKUP AND IS THE **ONLY AUTHORIZED SOURCE** FOR:

* T-SHIRT COLOR
* GRAPHIC DESIGN
* LOGOS
* WORDING
* TYPOGRAPHY
* LETTERING
* NUMBERS
* SYMBOLS
* ILLUSTRATIONS
* PRINT COLORS
* GRAPHIC COLORS
* GRAPHIC PLACEMENT
* GRAPHIC SCALE
* GRAPHIC PROPORTIONS
* GRAPHIC ORIENTATION
* GRAPHIC SPACING
* FRONT/BACK DESIGN DETAILS
* BRANDING
* LABEL GRAPHICS IF VISIBLE
* EMBLEMS
* DISTRESSING THAT IS PART OF THE PRINT
* SPECIAL DESIGN EFFECTS
* ALL OTHER CUSTOMER-SPECIFIC VISUAL DETAILS

**EVERY CUSTOMER-SPECIFIC DETAIL VISIBLE IN IMAGE #1 MUST BE PRESERVED.**

DO NOT REDESIGN, REINTERPRET, IMPROVE, CLEAN UP, SIMPLIFY, RESTYLE, RECOLOR, REPOSITION, OR RECREATE THE CUSTOMER'S ARTWORK DIFFERENTLY.

THE DESIGN IN IMAGE #1 IS LOCKED.

---

# IMAGE #2 — MOCKUP / PRESENTATION SOURCE ONLY

IMAGE #2 IS STRICTLY A **DISPLAY, GARMENT PRESENTATION, MATERIAL, AND PHOTOGRAPHY REFERENCE**.

USE IMAGE #2 ONLY TO DETERMINE:

* HOW THE T-SHIRT IS DISPLAYED
* OVERALL T-SHIRT SILHOUETTE
* GARMENT SHAPE
* GARMENT POSITION
* GARMENT ORIENTATION
* CAMERA ANGLE
* CAMERA DISTANCE
* PERSPECTIVE
* CROPPING
* T-SHIRT PROPORTIONS
* SLEEVE POSITION
* SLEEVE FALL
* COLLAR SHAPE
* BODY WIDTH
* BODY LENGTH
* NATURAL FABRIC DRAPE
* NATURAL WRINKLES
* NATURAL FOLDS
* FABRIC WEIGHT
* FABRIC THICKNESS
* COTTON TEXTURE
* REALISTIC SEAMS
* STITCHING BEHAVIOR
* FABRIC SHADOWS
* NATURAL HIGHLIGHTS
* REALISTIC DEPTH
* PHOTOGRAPHIC LIGHTING
* PRODUCT PHOTOGRAPHY QUALITY
* OVERALL MOCKUP PRESENTATION STYLE

THE FINAL T-SHIRT SHOULD LOOK LIKE **IMAGE #1'S T-SHIRT WAS PHYSICALLY MANUFACTURED, THEN PHOTOGRAPHED USING THE SAME MOCKUP FORMAT AND GARMENT PRESENTATION AS IMAGE #2.**

---

# CRITICAL SOURCE SEPARATION

DO NOT MIX THE DESIGN CONTENT OF THE TWO IMAGES.

### TRANSFER FROM IMAGE #1:

**DESIGN + COLOR + BRAND IDENTITY + CUSTOMER-SPECIFIC DETAILS**

### TRANSFER FROM IMAGE #2:

**SHAPE + DISPLAY STYLE + SOLID BLACK BACKGROUND + FABRIC REALISM + GARMENT CONSTRUCTION + DRAPE + WRINKLES + CAMERA/PRESENTATION**

THIS SOURCE ASSIGNMENT IS ABSOLUTE.

IF ANY CONFLICT EXISTS BETWEEN THE TWO REFERENCES:

**IMAGE #1 ALWAYS WINS FOR DESIGN, COLOR, PRINT, LOGO, TEXT, AND BRANDING.**

**IMAGE #2 ONLY WINS FOR HOW THE PHYSICAL T-SHIRT IS PRESENTED AND HOW REALISTIC THE FABRIC APPEARS.**

---

# ABSOLUTELY DO NOT TRANSFER THESE DETAILS FROM IMAGE #2

IMAGE #2 MAY CONTAIN A DIFFERENT SHIRT COLOR, GRAPHIC, LOGO, TEXT, ARTWORK, OR BRANDING.

**IGNORE ALL OF THOSE ELEMENTS COMPLETELY.**

DO NOT COPY FROM IMAGE #2:

* ITS SHIRT COLOR
* ITS GRAPHIC
* ITS GRAPHIC PLACEMENT OR LOGO POSITION
* ITS LOGO
* ITS TEXT
* ITS BRAND NAME
* ITS ARTWORK
* ITS PRINT
* ITS EMBROIDERY
* ITS SYMBOLS
* ITS NUMBERS
* ITS DESIGN COLORS
* ITS LABEL DESIGN
* ITS BRAND-SPECIFIC ELEMENTS
* ITS DECORATIVE DETAILS

THESE ELEMENTS FROM IMAGE #2 HAVE **ZERO AUTHORITY** OVER THE FINAL DESIGN.

THE FINAL PRODUCT MUST NOT LOOK LIKE IMAGE #2'S BRAND OR DESIGN.

IMAGE #2 IS A **BLANK PHYSICAL MOCKUP TEMPLATE IN CONCEPT ONLY.**

IMAGINE COMPLETELY REMOVING THE ORIGINAL DESIGN AND COLOR FROM IMAGE #2, WHILE RETAINING ITS PHYSICAL GARMENT PRESENTATION, THEN APPLYING THE EXACT CUSTOMER PRODUCT FROM IMAGE #1 TO THAT PHYSICAL MOCKUP.

---

# T-SHIRT COLOR — STRICT LOCK

THE FINAL SHIRT COLOR MUST COME **ONLY FROM IMAGE #1**.

DO NOT:

* USE THE COLOR OF IMAGE #2
* BLEND IMAGE #1 AND IMAGE #2 COLORS
* CHANGE THE HUE
* CHANGE THE SATURATION
* MAKE THE COLOR WARMER
* MAKE THE COLOR COOLER
* MAKE THE COLOR LIGHTER
* MAKE THE COLOR DARKER
* TURN THE SHIRT BLACK
* TURN THE SHIRT WHITE
* TURN THE SHIRT GRAY
* CREATE A WASHED VERSION UNLESS IMAGE #1 ALREADY SHOWS IT
* ADD VINTAGE FADING UNLESS IMAGE #1 ALREADY SHOWS IT

THE FABRIC MAY RECEIVE **NATURAL LIGHTING, SHADOWS, HIGHLIGHTS, AND FOLDS REQUIRED FOR PHOTOREALISM**, BUT ITS ACTUAL BASE COLOR MUST REMAIN FAITHFUL TO IMAGE #1.

**FABRIC STYLE FROM IMAGE #2 DOES NOT MEAN FABRIC COLOR FROM IMAGE #2.**

---

# CUSTOMER GRAPHIC — ZERO ALTERATION POLICY

THE GRAPHIC FROM IMAGE #1 MUST BE REPRODUCED WITH EXTREME FIDELITY.

PRESERVE:

* EXACT CONTENT
* EXACT SPELLING
* EXACT LETTERS
* EXACT NUMBERS
* EXACT WORD ORDER
* EXACT LOGO STRUCTURE
* EXACT SYMBOLS
* EXACT ARTWORK
* EXACT COLORS
* EXACT RELATIVE SIZE
* EXACT RELATIVE POSITION ON THE CUSTOMER'S SHIRT FROM IMAGE #1 — NOT THE GRAPHIC PLACEMENT FROM IMAGE #2
* EXACT PROPORTIONS
* EXACT ORIENTATION
* EXACT INTERNAL SPACING
* EXACT VISUAL HIERARCHY
* EXACT COMPOSITION

DO NOT:

* INVENT LETTERS
* MISSPELL WORDS
* CHANGE TYPOGRAPHY
* SUBSTITUTE FONTS
* ADD WORDS
* REMOVE WORDS
* CHANGE LOGOS
* REDRAW LOGOS DIFFERENTLY
* MODIFY SYMBOLS
* ADD DETAILS
* REMOVE DETAILS
* CHANGE COLORS
* CHANGE GRAPHIC SCALE WITHOUT PHYSICAL REASON
* MOVE THE GRAPHIC TO A DIFFERENT PART OF THE SHIRT
* COPY WHERE IMAGE #2'S GRAPHIC, LOGO, OR PRINT SITS ON ITS SHIRT
* RECENTER, RAISE, LOWER, OR SHIFT THE CUSTOMER'S LOGO TO MATCH IMAGE #2'S LAYOUT
* CENTER SOMETHING THAT IS INTENTIONALLY OFF-CENTER
* STRETCH THE ARTWORK
* SQUASH THE ARTWORK
* MIRROR THE ARTWORK
* ROTATE THE ARTWORK
* CROP THE ARTWORK
* TURN PRINT INTO EMBROIDERY
* TURN EMBROIDERY INTO PRINT
* ADD DISTRESSING
* REMOVE DISTRESSING
* GENERATE A "SIMILAR" VERSION

**DO NOT CREATE AN INTERPRETATION OF THE DESIGN. REPRODUCE THE DESIGN.**

---

# GRAPHIC APPLICATION TO REALISTIC FABRIC

WHEN PLACING IMAGE #1'S DESIGN ONTO THE REALISTIC T-SHIRT PRESENTATION FROM IMAGE #2:

THE ARTWORK MUST BEHAVE LIKE A **REAL PHYSICAL PRINT ON FABRIC**.

IF THE FABRIC WRINKLES, BENDS, FOLDS, OR CURVES:

* THE PRINT SHOULD NATURALLY FOLLOW THE FABRIC SURFACE.
* MINOR PHYSICAL WARPING CAUSED BY REAL FABRIC DRAPE IS ACCEPTABLE.
* THE UNDERLYING ARTWORK ITSELF MUST NOT BE REDESIGNED.
* DO NOT DISTORT LETTERS BEYOND WHAT REAL FABRIC WOULD CAUSE.
* DO NOT BREAK LOGOS.
* DO NOT REARRANGE ELEMENTS.
* DO NOT CREATE RANDOM GAPS.
* DO NOT ADD FAKE TEXTURES INSIDE THE GRAPHIC.
* DO NOT MAKE THE GRAPHIC FLOAT ABOVE THE SHIRT.
* DO NOT MAKE IT LOOK DIGITALLY PASTED ON.

THE PRINT MUST LOOK **PHYSICALLY APPLIED TO THE GARMENT**, WHILE REMAINING IDENTICAL TO THE CUSTOMER'S DESIGN.

---

# GARMENT STYLE FROM IMAGE #2

RECREATE THE PHYSICAL CHARACTERISTICS OF IMAGE #2'S T-SHIRT MOCKUP AS CLOSELY AS POSSIBLE.

MATCH:

* OVERALL CUT
* SILHOUETTE
* WIDTH
* LENGTH
* SHOULDER WIDTH
* SLEEVE LENGTH
* SLEEVE ANGLE
* SLEEVE OPENING
* COLLAR SIZE
* COLLAR THICKNESS
* COLLAR SHAPE
* BODY PROPORTION
* SIDE SHAPE
* HEM POSITION
* NATURAL GARMENT DRAPE
* FABRIC DENSITY
* FABRIC WEIGHT
* WRINKLE PATTERN STYLE
* CREASE DEPTH
* NATURAL FABRIC TENSION
* EDGE BEHAVIOR
* STITCHING REALISM

THE GOAL IS FOR SOMEONE VIEWING THE FINAL IMAGE TO IMMEDIATELY RECOGNIZE **IMAGE #2'S MOCKUP PRESENTATION STYLE**, WHILE SEEING **ONLY IMAGE #1'S ACTUAL PRODUCT DESIGN.**

---

# FABRIC REALISM

THE FINAL PRODUCT MUST HAVE THE HIGH-QUALITY PHYSICAL FABRIC APPEARANCE OF IMAGE #2.

CREATE REALISTIC:

* COTTON FIBERS
* SUBTLE FABRIC GRAIN
* NATURAL KNIT TEXTURE
* SEAMS
* COLLAR RIBBING
* SLEEVE HEMS
* BOTTOM HEM
* STITCHING
* FABRIC THICKNESS
* FOLD SHADOWS
* CONTACT SHADOWS
* MICRO-WRINKLES
* LARGE NATURAL FOLDS
* LIGHT ABSORPTION
* NATURAL HIGHLIGHTS
* SMALL TEXTURAL VARIATION

DO NOT OVERDO THE TEXTURE.

THE SHIRT SHOULD LOOK LIKE A **REAL, PROFESSIONALLY PHOTOGRAPHED GARMENT**, NOT A 3D MODEL, CGI RENDER, AI IMAGE, VECTOR MOCKUP, OR FLAT DIGITAL TEMPLATE.

---

# WRINKLES AND FOLDS

USE IMAGE #2 AS THE PRIMARY REFERENCE FOR HOW THE FABRIC NATURALLY LAYS.

WRINKLES MUST:

* FOLLOW THE PHYSICS OF THE GARMENT
* APPEAR NATURAL
* BE CONSISTENT WITH THE FABRIC WEIGHT
* OCCUR AROUND REAL TENSION/COMPRESSION POINTS
* CREATE BELIEVABLE LIGHT AND SHADOW
* NOT RANDOMLY DESTROY OR OBSCURE THE CUSTOMER'S GRAPHIC

DO NOT CREATE EXCESSIVE WRINKLES SIMPLY TO MAKE THE IMAGE LOOK REALISTIC.

THE PRODUCT SHOULD REMAIN **CLEAN AND COMMERCIAL**, WHILE STILL HAVING NATURAL FABRIC CHARACTER.

---

# PRODUCT CONSTRUCTION REALISM

ENSURE THAT THE T-SHIRT REMAINS PHYSICALLY POSSIBLE.

CHECK:

* TWO CORRECT SLEEVES
* SYMMETRICAL BASIC CONSTRUCTION WHERE APPROPRIATE
* REALISTIC ARMHOLES
* CORRECT NECK OPENING
* CONTINUOUS COLLAR
* PROPER SHOULDER SEAMS
* CORRECT SIDE SEAMS IF VISIBLE
* REALISTIC SLEEVE HEMS
* REALISTIC BOTTOM HEM
* NO DUPLICATE EDGES
* NO MELTED FABRIC
* NO FLOATING MATERIAL
* NO IMPOSSIBLE FOLDS
* NO EXTRA SLEEVES
* NO MISSING SECTIONS
* NO TWISTED GEOMETRY
* NO RANDOM CUTOUTS

---

# CAMERA AND COMPOSITION

MATCH IMAGE #2'S PRESENTATION AS CLOSELY AS POSSIBLE.

PRESERVE ITS:

* VIEWING ANGLE
* CAMERA HEIGHT
* CAMERA DIRECTION
* DISTANCE
* PERSPECTIVE
* SCALE WITHIN FRAME
* PRODUCT PLACEMENT
* CROPPING
* NEGATIVE SPACE
* ORIENTATION
* VISUAL BALANCE

DO NOT RANDOMLY CHANGE THE CAMERA ANGLE.

DO NOT CREATE A DIFFERENT MOCKUP CONCEPT.

DO NOT TURN A FLAT-LAY INTO A HANGING SHIRT.

DO NOT TURN A HANGING SHIRT INTO A MODEL-WORN SHIRT.

DO NOT TURN A FRONT VIEW INTO A THREE-QUARTER VIEW.

**FOLLOW WHATEVER DISPLAY FORMAT IMAGE #2 ACTUALLY USES.**

---

# LIGHTING AND SHADOWS

USE IMAGE #2 AS THE LIGHTING REFERENCE.

MATCH ITS:

* LIGHT DIRECTION
* LIGHT SOFTNESS
* SHADOW DIRECTION
* SHADOW INTENSITY
* CONTRAST
* HIGHLIGHT BEHAVIOR
* EXPOSURE
* NATURAL DEPTH

LIGHTING MUST AFFECT IMAGE #1'S SHIRT COLOR NATURALLY WITHOUT CHANGING THE PRODUCT'S ACTUAL COLOR IDENTITY.

SHADOWS MUST BE PHYSICALLY CONSISTENT WITH THE FOLDS AND SHAPE OF THE GARMENT.

---

# BACKGROUND

THE BACKGROUND MUST BE THE **SAME SOLID BLACK STUDIO BACKGROUND AS IMAGE #2**.

THIS IS REQUIRED. DO NOT USE:

* THE BACKGROUND FROM IMAGE #1
* WHITE
* GRAY
* PAPER
* A TABLE
* A WALL
* A ROOM
* A LIFESTYLE SCENE
* ANY COLOR OTHER THAN THE BLACK STUDIO FIELD IN IMAGE #2

IMAGE #2 IS A BLACK-BACKGROUND PRODUCT SHOT. THE FINAL IMAGE MUST ALSO BE A BLACK-BACKGROUND PRODUCT SHOT.

THE BACKGROUND MUST NOT INTRODUCE:

* NEW PROPS
* RANDOM OBJECTS
* DECORATIONS
* PEOPLE
* HANDS
* BRANDING
* WATERMARKS
* ADDITIONAL TEXT

THE T-SHIRT MUST REMAIN THE CLEAR PRODUCT FOCUS.

---

# ZERO CREATIVE FREEDOM RULE

THIS IS A **CUSTOMER PRODUCT REPRODUCTION TASK**, NOT A CREATIVE DESIGN TASK.

YOU ARE NOT AUTHORIZED TO MAKE THE PRODUCT:

* "BETTER"
* "MORE STYLISH"
* "MORE BALANCED"
* "MORE PROFESSIONAL"
* "MORE MINIMAL"
* "MORE LUXURIOUS"
* "MORE TRENDY"
* "MORE AESTHETIC"

DO NOT MAKE CREATIVE DECISIONS ABOUT THE CUSTOMER'S PRODUCT.

YOUR JOB IS TO **PRESERVE IMAGE #1 AND PRESENT IT THROUGH IMAGE #2'S MOCKUP SYSTEM.**

WHEN UNCERTAIN ABOUT A CUSTOMER DESIGN DETAIL, PRESERVE IMAGE #1 RATHER THAN INVENTING SOMETHING.

---

# STRICT NEGATIVE CONSTRAINTS

ABSOLUTELY NO:

* DESIGN CHANGES
* COLOR CHANGES
* LOGO CHANGES
* TEXT CHANGES
* MISSPELLINGS
* FONT SUBSTITUTIONS
* EXTRA GRAPHICS
* MISSING GRAPHICS
* GRAPHIC REPLACEMENT
* GRAPHIC REDESIGN
* COLOR TRANSFER FROM IMAGE #2
* ARTWORK TRANSFER FROM IMAGE #2
* BRANDING TRANSFER FROM IMAGE #2
* HYBRIDIZATION OF BOTH DESIGNS
* RANDOM DISTRESSING
* RANDOM WASHING
* RANDOM FADING
* EXTRA LABELS
* EXTRA TAGS
* EXTRA STITCHING DETAILS NOT REQUIRED BY THE GARMENT
* NEW ACCESSORIES
* NEW OBJECTS
* DUPLICATED GRAPHICS
* MIRRORED GRAPHICS
* AI-GENERATED LETTERING
* FAKE WORDS
* WARPED LOGOS
* MELTED FABRIC
* FLOATING GRAPHICS
* PLASTIC-LOOKING FABRIC
* OVERLY SMOOTH CGI SURFACES
* CARTOON APPEARANCE
* ILLUSTRATED APPEARANCE
* 3D-RENDER APPEARANCE
* UNREALISTIC SHADOWS
* UNREALISTIC FOLDS
* ANATOMICAL ELEMENTS IF NO MODEL EXISTS IN #2
* WATERMARKS
* CAPTIONS
* EXTRA TEXT OUTSIDE THE CUSTOMER'S ACTUAL DESIGN

---

# PRIORITY ORDER

IF ANY INSTRUCTION OR REFERENCE DETAIL CONFLICTS, FOLLOW THIS PRIORITY ORDER:

### PRIORITY 1 — IMAGE #1 CUSTOMER PRODUCT IDENTITY

DESIGN, ARTWORK, GRAPHICS, LOGOS, TEXT, COLORS, BRANDING, AND CUSTOMER-SPECIFIC DETAILS MUST NEVER CHANGE.

### PRIORITY 2 — IMAGE #2 MOCKUP STRUCTURE

MATCH ITS T-SHIRT SHAPE, DISPLAY, ORIENTATION, CAMERA, DRAPE, MATERIAL REALISM, WRINKLES, AND CONSTRUCTION.

### PRIORITY 3 — PHOTOREALISM

MAKE THE COMBINED RESULT LOOK LIKE AN ACTUAL PHYSICAL T-SHIRT THAT WAS PROFESSIONALLY PHOTOGRAPHED.

IF PHOTOREALISM WOULD REQUIRE ALTERING THE CUSTOMER'S DESIGN, **PRESERVE THE CUSTOMER'S DESIGN INSTEAD.**

---

# INTERNAL VALIDATION BEFORE FINAL OUTPUT

BEFORE PRODUCING THE FINAL IMAGE, INTERNALLY VERIFY ALL OF THE FOLLOWING:

1. IS THE SHIRT COLOR FROM IMAGE #1 AND NOT IMAGE #2?
2. IS 100% OF THE CUSTOMER ARTWORK FROM IMAGE #1?
3. DID ANY GRAPHIC, LOGO, TEXT, OR BRANDING FROM IMAGE #2 ACCIDENTALLY TRANSFER? IF YES, REMOVE IT.
4. IS ALL CUSTOMER TEXT SPELLED EXACTLY AS SHOWN IN IMAGE #1?
5. ARE ALL LOGOS AND SYMBOLS STRUCTURALLY IDENTICAL TO IMAGE #1?
6. ARE GRAPHIC COLORS PRESERVED?
7. IS THE LOGO/GRAPHIC PLACED WHERE IT IS ON IMAGE #1, NOT WHERE IMAGE #2'S GRAPHIC SITS?
8. IS GRAPHIC SCALE PRESERVED FROM IMAGE #1?
9. IS THE BACKGROUND THE SAME SOLID BLACK STUDIO FIELD AS IMAGE #2?
10. DOES THE FABRIC TEXTURE AND WEIGHT RESEMBLE IMAGE #2?
11. DO THE WRINKLES AND FOLDS LOOK PHYSICALLY REAL?
12. DOES THE CAMERA ANGLE MATCH IMAGE #2?
13. DOES THE PRODUCT OCCUPY THE FRAME SIMILARLY TO IMAGE #2?
14. ARE THE COLLAR, SLEEVES, HEMS, AND SEAMS PHYSICALLY CORRECT?
15. ARE THERE ANY AI ARTIFACTS?
16. ARE THERE ANY EXTRA LETTERS OR FAKE TEXT?
17. ARE THERE ANY DUPLICATED OR DEFORMED GRAPHICS?
18. DOES THE PRINT NATURALLY FOLLOW THE FABRIC WITHOUT CHANGING THE ORIGINAL ARTWORK?
19. DOES THE IMAGE LOOK LIKE A REAL PHOTOGRAPH RATHER THAN A DIGITAL MOCKUP?
20. WOULD THE CUSTOMER RECOGNIZE THEIR IMAGE #1 PRODUCT AS **UNCHANGED**?

IF ANY ANSWER IS INCORRECT, **CORRECT IT BEFORE GENERATING THE FINAL RESULT.**

---

# FINAL OUTPUT REQUIREMENT

THE FINAL RESULT MUST LOOK AS THOUGH:

**THE EXACT CUSTOMER T-SHIRT FROM IMAGE #1 WAS PHYSICALLY PRODUCED USING THE REALISTIC GARMENT MATERIAL, SILHOUETTE, DRAPE, WRINKLES, CONSTRUCTION, PHOTOGRAPHY, AND DISPLAY PRESENTATION SHOWN IN IMAGE #2.**

IMAGE #1'S **DESIGN + COLOR + BRANDING + PRODUCT DETAILS MUST REMAIN UNCHANGED.**

IMAGE #2'S **DESIGN + COLOR + GRAPHICS + BRANDING MUST NOT APPEAR ANYWHERE IN THE FINAL RESULT.**

USE IMAGE #2 **ONLY AS THE PHYSICAL MOCKUP AND PRESENTATION REFERENCE.**

THE FINAL IMAGE MUST BE:

**PHOTOREALISTIC.
COMMERCIAL QUALITY.
CUSTOMER-READY.
TEXTURALLY REALISTIC.
PHYSICALLY BELIEVABLE.
100% FAITHFUL TO IMAGE #1'S PRODUCT DESIGN.
100% BASED ON IMAGE #2'S MOCKUP PRESENTATION STYLE.
ZERO UNAUTHORIZED DESIGN CHANGES.
ZERO AI ARTIFACTS.**`,
    refs: [],
    aspect: "portrait",
  },
  {
    id: 4,
    name: "Raspberry Worldwide Tee",
    garment: "Tee",
    shot: "Flat lay",
    summary: "Washed charcoal tee with a weathered oval graphic.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 5,
    name: "Raspberry Hills Tee",
    garment: "Tee",
    shot: "Flat lay",
    summary: "Oversized off-white tee, frayed collar, cracked vintage print.",
    prompt: `## PRIMARY OBJECTIVE

CREATE A **100% PHOTOREALISTIC, PROFESSIONAL E-COMMERCE PRODUCT MOCKUP** USING EXACTLY TWO REFERENCE IMAGES.

THE FINAL IMAGE MUST SHOW THE **EXACT CUSTOMER T-SHIRT FROM IMAGE #1** — INCLUDING ITS EXACT SHIRT COLOR, GRAPHICS, PRINTS, TEXT, LOGOS, ARTWORK, DESIGN DETAILS, AND VISUAL IDENTITY — BUT THE T-SHIRT MUST BE **PRESENTED, SHAPED, POSITIONED, AND PHOTOGRAPHED IN THE SAME MOCKUP STYLE AS IMAGE #2**.

THE SIMPLE RULE IS:

**IMAGE #1 = THE PRODUCT / DESIGN SOURCE.**
**IMAGE #2 = THE PRESENTATION / MOCKUP SOURCE.**

IMAGE #2 MUST NEVER OVERRIDE THE CUSTOMER'S ACTUAL PRODUCT DESIGN FROM IMAGE #1.

---

# IMAGE ASSIGNMENTS

## IMAGE #1 — ABSOLUTE PRODUCT DESIGN SOURCE

IMAGE #1 IS THE CUSTOMER'S ACTUAL T-SHIRT MOCKUP AND IS THE **ONLY AUTHORIZED SOURCE** FOR:

* T-SHIRT COLOR
* GRAPHIC DESIGN
* LOGOS
* WORDING
* TYPOGRAPHY
* LETTERING
* NUMBERS
* SYMBOLS
* ILLUSTRATIONS
* PRINT COLORS
* GRAPHIC COLORS
* GRAPHIC PLACEMENT
* GRAPHIC SCALE
* GRAPHIC PROPORTIONS
* GRAPHIC ORIENTATION
* GRAPHIC SPACING
* FRONT/BACK DESIGN DETAILS
* BRANDING
* LABEL GRAPHICS IF VISIBLE
* EMBLEMS
* DISTRESSING THAT IS PART OF THE PRINT
* SPECIAL DESIGN EFFECTS
* ALL OTHER CUSTOMER-SPECIFIC VISUAL DETAILS

**EVERY CUSTOMER-SPECIFIC DETAIL VISIBLE IN IMAGE #1 MUST BE PRESERVED.**

DO NOT REDESIGN, REINTERPRET, IMPROVE, CLEAN UP, SIMPLIFY, RESTYLE, RECOLOR, REPOSITION, OR RECREATE THE CUSTOMER'S ARTWORK DIFFERENTLY.

THE DESIGN IN IMAGE #1 IS LOCKED.

---

# IMAGE #2 — MOCKUP / PRESENTATION SOURCE ONLY

IMAGE #2 IS STRICTLY A **DISPLAY, GARMENT PRESENTATION, MATERIAL, AND PHOTOGRAPHY REFERENCE**.

USE IMAGE #2 ONLY TO DETERMINE:

* HOW THE T-SHIRT IS DISPLAYED
* OVERALL T-SHIRT SILHOUETTE
* GARMENT SHAPE
* GARMENT POSITION
* GARMENT ORIENTATION
* CAMERA ANGLE
* CAMERA DISTANCE
* PERSPECTIVE
* CROPPING
* T-SHIRT PROPORTIONS
* SLEEVE POSITION
* SLEEVE FALL
* COLLAR SHAPE
* BODY WIDTH
* BODY LENGTH
* NATURAL FABRIC DRAPE
* NATURAL WRINKLES
* NATURAL FOLDS
* FABRIC WEIGHT
* FABRIC THICKNESS
* COTTON TEXTURE
* REALISTIC SEAMS
* STITCHING BEHAVIOR
* FABRIC SHADOWS
* NATURAL HIGHLIGHTS
* REALISTIC DEPTH
* PHOTOGRAPHIC LIGHTING
* PRODUCT PHOTOGRAPHY QUALITY
* OVERALL MOCKUP PRESENTATION STYLE

THE FINAL T-SHIRT SHOULD LOOK LIKE **IMAGE #1'S T-SHIRT WAS PHYSICALLY MANUFACTURED, THEN PHOTOGRAPHED USING THE SAME MOCKUP FORMAT AND GARMENT PRESENTATION AS IMAGE #2.**

---

# CRITICAL SOURCE SEPARATION

DO NOT MIX THE DESIGN CONTENT OF THE TWO IMAGES.

### TRANSFER FROM IMAGE #1:

**DESIGN + COLOR + BRAND IDENTITY + CUSTOMER-SPECIFIC DETAILS**

### TRANSFER FROM IMAGE #2:

**SHAPE + DISPLAY STYLE + SOLID BLACK BACKGROUND + FABRIC REALISM + GARMENT CONSTRUCTION + DRAPE + WRINKLES + CAMERA/PRESENTATION**

THIS SOURCE ASSIGNMENT IS ABSOLUTE.

IF ANY CONFLICT EXISTS BETWEEN THE TWO REFERENCES:

**IMAGE #1 ALWAYS WINS FOR DESIGN, COLOR, PRINT, LOGO, TEXT, AND BRANDING.**

**IMAGE #2 ONLY WINS FOR HOW THE PHYSICAL T-SHIRT IS PRESENTED AND HOW REALISTIC THE FABRIC APPEARS.**

---

# ABSOLUTELY DO NOT TRANSFER THESE DETAILS FROM IMAGE #2

IMAGE #2 MAY CONTAIN A DIFFERENT SHIRT COLOR, GRAPHIC, LOGO, TEXT, ARTWORK, OR BRANDING.

**IGNORE ALL OF THOSE ELEMENTS COMPLETELY.**

DO NOT COPY FROM IMAGE #2:

* ITS SHIRT COLOR
* ITS GRAPHIC
* ITS GRAPHIC PLACEMENT OR LOGO POSITION
* ITS LOGO
* ITS TEXT
* ITS BRAND NAME
* ITS ARTWORK
* ITS PRINT
* ITS EMBROIDERY
* ITS SYMBOLS
* ITS NUMBERS
* ITS DESIGN COLORS
* ITS LABEL DESIGN
* ITS BRAND-SPECIFIC ELEMENTS
* ITS DECORATIVE DETAILS

THESE ELEMENTS FROM IMAGE #2 HAVE **ZERO AUTHORITY** OVER THE FINAL DESIGN.

THE FINAL PRODUCT MUST NOT LOOK LIKE IMAGE #2'S BRAND OR DESIGN.

IMAGE #2 IS A **BLANK PHYSICAL MOCKUP TEMPLATE IN CONCEPT ONLY.**

IMAGINE COMPLETELY REMOVING THE ORIGINAL DESIGN AND COLOR FROM IMAGE #2, WHILE RETAINING ITS PHYSICAL GARMENT PRESENTATION, THEN APPLYING THE EXACT CUSTOMER PRODUCT FROM IMAGE #1 TO THAT PHYSICAL MOCKUP.

---

# T-SHIRT COLOR — STRICT LOCK

THE FINAL SHIRT COLOR MUST COME **ONLY FROM IMAGE #1**.

DO NOT:

* USE THE COLOR OF IMAGE #2
* BLEND IMAGE #1 AND IMAGE #2 COLORS
* CHANGE THE HUE
* CHANGE THE SATURATION
* MAKE THE COLOR WARMER
* MAKE THE COLOR COOLER
* MAKE THE COLOR LIGHTER
* MAKE THE COLOR DARKER
* TURN THE SHIRT BLACK
* TURN THE SHIRT WHITE
* TURN THE SHIRT GRAY
* CREATE A WASHED VERSION UNLESS IMAGE #1 ALREADY SHOWS IT
* ADD VINTAGE FADING UNLESS IMAGE #1 ALREADY SHOWS IT

THE FABRIC MAY RECEIVE **NATURAL LIGHTING, SHADOWS, HIGHLIGHTS, AND FOLDS REQUIRED FOR PHOTOREALISM**, BUT ITS ACTUAL BASE COLOR MUST REMAIN FAITHFUL TO IMAGE #1.

**FABRIC STYLE FROM IMAGE #2 DOES NOT MEAN FABRIC COLOR FROM IMAGE #2.**

---

# CUSTOMER GRAPHIC — ZERO ALTERATION POLICY

THE GRAPHIC FROM IMAGE #1 MUST BE REPRODUCED WITH EXTREME FIDELITY.

PRESERVE:

* EXACT CONTENT
* EXACT SPELLING
* EXACT LETTERS
* EXACT NUMBERS
* EXACT WORD ORDER
* EXACT LOGO STRUCTURE
* EXACT SYMBOLS
* EXACT ARTWORK
* EXACT COLORS
* EXACT RELATIVE SIZE
* EXACT RELATIVE POSITION ON THE CUSTOMER'S SHIRT FROM IMAGE #1 — NOT THE GRAPHIC PLACEMENT FROM IMAGE #2
* EXACT PROPORTIONS
* EXACT ORIENTATION
* EXACT INTERNAL SPACING
* EXACT VISUAL HIERARCHY
* EXACT COMPOSITION

DO NOT:

* INVENT LETTERS
* MISSPELL WORDS
* CHANGE TYPOGRAPHY
* SUBSTITUTE FONTS
* ADD WORDS
* REMOVE WORDS
* CHANGE LOGOS
* REDRAW LOGOS DIFFERENTLY
* MODIFY SYMBOLS
* ADD DETAILS
* REMOVE DETAILS
* CHANGE COLORS
* CHANGE GRAPHIC SCALE WITHOUT PHYSICAL REASON
* MOVE THE GRAPHIC TO A DIFFERENT PART OF THE SHIRT
* COPY WHERE IMAGE #2'S GRAPHIC, LOGO, OR PRINT SITS ON ITS SHIRT
* RECENTER, RAISE, LOWER, OR SHIFT THE CUSTOMER'S LOGO TO MATCH IMAGE #2'S LAYOUT
* CENTER SOMETHING THAT IS INTENTIONALLY OFF-CENTER
* STRETCH THE ARTWORK
* SQUASH THE ARTWORK
* MIRROR THE ARTWORK
* ROTATE THE ARTWORK
* CROP THE ARTWORK
* TURN PRINT INTO EMBROIDERY
* TURN EMBROIDERY INTO PRINT
* ADD DISTRESSING
* REMOVE DISTRESSING
* GENERATE A "SIMILAR" VERSION

**DO NOT CREATE AN INTERPRETATION OF THE DESIGN. REPRODUCE THE DESIGN.**

---

# GRAPHIC APPLICATION TO REALISTIC FABRIC

WHEN PLACING IMAGE #1'S DESIGN ONTO THE REALISTIC T-SHIRT PRESENTATION FROM IMAGE #2:

THE ARTWORK MUST BEHAVE LIKE A **REAL PHYSICAL PRINT ON FABRIC**.

IF THE FABRIC WRINKLES, BENDS, FOLDS, OR CURVES:

* THE PRINT SHOULD NATURALLY FOLLOW THE FABRIC SURFACE.
* MINOR PHYSICAL WARPING CAUSED BY REAL FABRIC DRAPE IS ACCEPTABLE.
* THE UNDERLYING ARTWORK ITSELF MUST NOT BE REDESIGNED.
* DO NOT DISTORT LETTERS BEYOND WHAT REAL FABRIC WOULD CAUSE.
* DO NOT BREAK LOGOS.
* DO NOT REARRANGE ELEMENTS.
* DO NOT CREATE RANDOM GAPS.
* DO NOT ADD FAKE TEXTURES INSIDE THE GRAPHIC.
* DO NOT MAKE THE GRAPHIC FLOAT ABOVE THE SHIRT.
* DO NOT MAKE IT LOOK DIGITALLY PASTED ON.

THE PRINT MUST LOOK **PHYSICALLY APPLIED TO THE GARMENT**, WHILE REMAINING IDENTICAL TO THE CUSTOMER'S DESIGN.

---

# GARMENT STYLE FROM IMAGE #2

RECREATE THE PHYSICAL CHARACTERISTICS OF IMAGE #2'S T-SHIRT MOCKUP AS CLOSELY AS POSSIBLE.

MATCH:

* OVERALL CUT
* SILHOUETTE
* WIDTH
* LENGTH
* SHOULDER WIDTH
* SLEEVE LENGTH
* SLEEVE ANGLE
* SLEEVE OPENING
* COLLAR SIZE
* COLLAR THICKNESS
* COLLAR SHAPE
* BODY PROPORTION
* SIDE SHAPE
* HEM POSITION
* NATURAL GARMENT DRAPE
* FABRIC DENSITY
* FABRIC WEIGHT
* WRINKLE PATTERN STYLE
* CREASE DEPTH
* NATURAL FABRIC TENSION
* EDGE BEHAVIOR
* STITCHING REALISM

THE GOAL IS FOR SOMEONE VIEWING THE FINAL IMAGE TO IMMEDIATELY RECOGNIZE **IMAGE #2'S MOCKUP PRESENTATION STYLE**, WHILE SEEING **ONLY IMAGE #1'S ACTUAL PRODUCT DESIGN.**

---

# FABRIC REALISM

THE FINAL PRODUCT MUST HAVE THE HIGH-QUALITY PHYSICAL FABRIC APPEARANCE OF IMAGE #2.

CREATE REALISTIC:

* COTTON FIBERS
* SUBTLE FABRIC GRAIN
* NATURAL KNIT TEXTURE
* SEAMS
* COLLAR RIBBING
* SLEEVE HEMS
* BOTTOM HEM
* STITCHING
* FABRIC THICKNESS
* FOLD SHADOWS
* CONTACT SHADOWS
* MICRO-WRINKLES
* LARGE NATURAL FOLDS
* LIGHT ABSORPTION
* NATURAL HIGHLIGHTS
* SMALL TEXTURAL VARIATION

DO NOT OVERDO THE TEXTURE.

THE SHIRT SHOULD LOOK LIKE A **REAL, PROFESSIONALLY PHOTOGRAPHED GARMENT**, NOT A 3D MODEL, CGI RENDER, AI IMAGE, VECTOR MOCKUP, OR FLAT DIGITAL TEMPLATE.

---

# WRINKLES AND FOLDS

USE IMAGE #2 AS THE PRIMARY REFERENCE FOR HOW THE FABRIC NATURALLY LAYS.

WRINKLES MUST:

* FOLLOW THE PHYSICS OF THE GARMENT
* APPEAR NATURAL
* BE CONSISTENT WITH THE FABRIC WEIGHT
* OCCUR AROUND REAL TENSION/COMPRESSION POINTS
* CREATE BELIEVABLE LIGHT AND SHADOW
* NOT RANDOMLY DESTROY OR OBSCURE THE CUSTOMER'S GRAPHIC

DO NOT CREATE EXCESSIVE WRINKLES SIMPLY TO MAKE THE IMAGE LOOK REALISTIC.

THE PRODUCT SHOULD REMAIN **CLEAN AND COMMERCIAL**, WHILE STILL HAVING NATURAL FABRIC CHARACTER.

---

# PRODUCT CONSTRUCTION REALISM

ENSURE THAT THE T-SHIRT REMAINS PHYSICALLY POSSIBLE.

CHECK:

* TWO CORRECT SLEEVES
* SYMMETRICAL BASIC CONSTRUCTION WHERE APPROPRIATE
* REALISTIC ARMHOLES
* CORRECT NECK OPENING
* CONTINUOUS COLLAR
* PROPER SHOULDER SEAMS
* CORRECT SIDE SEAMS IF VISIBLE
* REALISTIC SLEEVE HEMS
* REALISTIC BOTTOM HEM
* NO DUPLICATE EDGES
* NO MELTED FABRIC
* NO FLOATING MATERIAL
* NO IMPOSSIBLE FOLDS
* NO EXTRA SLEEVES
* NO MISSING SECTIONS
* NO TWISTED GEOMETRY
* NO RANDOM CUTOUTS

---

# CAMERA AND COMPOSITION

MATCH IMAGE #2'S PRESENTATION AS CLOSELY AS POSSIBLE.

PRESERVE ITS:

* VIEWING ANGLE
* CAMERA HEIGHT
* CAMERA DIRECTION
* DISTANCE
* PERSPECTIVE
* SCALE WITHIN FRAME
* PRODUCT PLACEMENT
* CROPPING
* NEGATIVE SPACE
* ORIENTATION
* VISUAL BALANCE

DO NOT RANDOMLY CHANGE THE CAMERA ANGLE.

DO NOT CREATE A DIFFERENT MOCKUP CONCEPT.

DO NOT TURN A FLAT-LAY INTO A HANGING SHIRT.

DO NOT TURN A HANGING SHIRT INTO A MODEL-WORN SHIRT.

DO NOT TURN A FRONT VIEW INTO A THREE-QUARTER VIEW.

**FOLLOW WHATEVER DISPLAY FORMAT IMAGE #2 ACTUALLY USES.**

---

# LIGHTING AND SHADOWS

USE IMAGE #2 AS THE LIGHTING REFERENCE.

MATCH ITS:

* LIGHT DIRECTION
* LIGHT SOFTNESS
* SHADOW DIRECTION
* SHADOW INTENSITY
* CONTRAST
* HIGHLIGHT BEHAVIOR
* EXPOSURE
* NATURAL DEPTH

LIGHTING MUST AFFECT IMAGE #1'S SHIRT COLOR NATURALLY WITHOUT CHANGING THE PRODUCT'S ACTUAL COLOR IDENTITY.

SHADOWS MUST BE PHYSICALLY CONSISTENT WITH THE FOLDS AND SHAPE OF THE GARMENT.

---

# BACKGROUND

THE BACKGROUND MUST BE THE **SAME SOLID BLACK STUDIO BACKGROUND AS IMAGE #2**.

THIS IS REQUIRED. DO NOT USE:

* THE BACKGROUND FROM IMAGE #1
* WHITE
* GRAY
* PAPER
* A TABLE
* A WALL
* A ROOM
* A LIFESTYLE SCENE
* ANY COLOR OTHER THAN THE BLACK STUDIO FIELD IN IMAGE #2

IMAGE #2 IS A BLACK-BACKGROUND PRODUCT SHOT. THE FINAL IMAGE MUST ALSO BE A BLACK-BACKGROUND PRODUCT SHOT.

THE BACKGROUND MUST NOT INTRODUCE:

* NEW PROPS
* RANDOM OBJECTS
* DECORATIONS
* PEOPLE
* HANDS
* BRANDING
* WATERMARKS
* ADDITIONAL TEXT

THE T-SHIRT MUST REMAIN THE CLEAR PRODUCT FOCUS.

---

# ZERO CREATIVE FREEDOM RULE

THIS IS A **CUSTOMER PRODUCT REPRODUCTION TASK**, NOT A CREATIVE DESIGN TASK.

YOU ARE NOT AUTHORIZED TO MAKE THE PRODUCT:

* "BETTER"
* "MORE STYLISH"
* "MORE BALANCED"
* "MORE PROFESSIONAL"
* "MORE MINIMAL"
* "MORE LUXURIOUS"
* "MORE TRENDY"
* "MORE AESTHETIC"

DO NOT MAKE CREATIVE DECISIONS ABOUT THE CUSTOMER'S PRODUCT.

YOUR JOB IS TO **PRESERVE IMAGE #1 AND PRESENT IT THROUGH IMAGE #2'S MOCKUP SYSTEM.**

WHEN UNCERTAIN ABOUT A CUSTOMER DESIGN DETAIL, PRESERVE IMAGE #1 RATHER THAN INVENTING SOMETHING.

---

# STRICT NEGATIVE CONSTRAINTS

ABSOLUTELY NO:

* DESIGN CHANGES
* COLOR CHANGES
* LOGO CHANGES
* TEXT CHANGES
* MISSPELLINGS
* FONT SUBSTITUTIONS
* EXTRA GRAPHICS
* MISSING GRAPHICS
* GRAPHIC REPLACEMENT
* GRAPHIC REDESIGN
* COLOR TRANSFER FROM IMAGE #2
* ARTWORK TRANSFER FROM IMAGE #2
* BRANDING TRANSFER FROM IMAGE #2
* HYBRIDIZATION OF BOTH DESIGNS
* RANDOM DISTRESSING
* RANDOM WASHING
* RANDOM FADING
* EXTRA LABELS
* EXTRA TAGS
* EXTRA STITCHING DETAILS NOT REQUIRED BY THE GARMENT
* NEW ACCESSORIES
* NEW OBJECTS
* DUPLICATED GRAPHICS
* MIRRORED GRAPHICS
* AI-GENERATED LETTERING
* FAKE WORDS
* WARPED LOGOS
* MELTED FABRIC
* FLOATING GRAPHICS
* PLASTIC-LOOKING FABRIC
* OVERLY SMOOTH CGI SURFACES
* CARTOON APPEARANCE
* ILLUSTRATED APPEARANCE
* 3D-RENDER APPEARANCE
* UNREALISTIC SHADOWS
* UNREALISTIC FOLDS
* ANATOMICAL ELEMENTS IF NO MODEL EXISTS IN #2
* WATERMARKS
* CAPTIONS
* EXTRA TEXT OUTSIDE THE CUSTOMER'S ACTUAL DESIGN

---

# PRIORITY ORDER

IF ANY INSTRUCTION OR REFERENCE DETAIL CONFLICTS, FOLLOW THIS PRIORITY ORDER:

### PRIORITY 1 — IMAGE #1 CUSTOMER PRODUCT IDENTITY

DESIGN, ARTWORK, GRAPHICS, LOGOS, TEXT, COLORS, BRANDING, AND CUSTOMER-SPECIFIC DETAILS MUST NEVER CHANGE.

### PRIORITY 2 — IMAGE #2 MOCKUP STRUCTURE

MATCH ITS T-SHIRT SHAPE, DISPLAY, ORIENTATION, CAMERA, DRAPE, MATERIAL REALISM, WRINKLES, AND CONSTRUCTION.

### PRIORITY 3 — PHOTOREALISM

MAKE THE COMBINED RESULT LOOK LIKE AN ACTUAL PHYSICAL T-SHIRT THAT WAS PROFESSIONALLY PHOTOGRAPHED.

IF PHOTOREALISM WOULD REQUIRE ALTERING THE CUSTOMER'S DESIGN, **PRESERVE THE CUSTOMER'S DESIGN INSTEAD.**

---

# INTERNAL VALIDATION BEFORE FINAL OUTPUT

BEFORE PRODUCING THE FINAL IMAGE, INTERNALLY VERIFY ALL OF THE FOLLOWING:

1. IS THE SHIRT COLOR FROM IMAGE #1 AND NOT IMAGE #2?
2. IS 100% OF THE CUSTOMER ARTWORK FROM IMAGE #1?
3. DID ANY GRAPHIC, LOGO, TEXT, OR BRANDING FROM IMAGE #2 ACCIDENTALLY TRANSFER? IF YES, REMOVE IT.
4. IS ALL CUSTOMER TEXT SPELLED EXACTLY AS SHOWN IN IMAGE #1?
5. ARE ALL LOGOS AND SYMBOLS STRUCTURALLY IDENTICAL TO IMAGE #1?
6. ARE GRAPHIC COLORS PRESERVED?
7. IS THE LOGO/GRAPHIC PLACED WHERE IT IS ON IMAGE #1, NOT WHERE IMAGE #2'S GRAPHIC SITS?
8. IS GRAPHIC SCALE PRESERVED FROM IMAGE #1?
9. IS THE BACKGROUND THE SAME SOLID BLACK STUDIO FIELD AS IMAGE #2?
10. DOES THE FABRIC TEXTURE AND WEIGHT RESEMBLE IMAGE #2?
11. DO THE WRINKLES AND FOLDS LOOK PHYSICALLY REAL?
12. DOES THE CAMERA ANGLE MATCH IMAGE #2?
13. DOES THE PRODUCT OCCUPY THE FRAME SIMILARLY TO IMAGE #2?
14. ARE THE COLLAR, SLEEVES, HEMS, AND SEAMS PHYSICALLY CORRECT?
15. ARE THERE ANY AI ARTIFACTS?
16. ARE THERE ANY EXTRA LETTERS OR FAKE TEXT?
17. ARE THERE ANY DUPLICATED OR DEFORMED GRAPHICS?
18. DOES THE PRINT NATURALLY FOLLOW THE FABRIC WITHOUT CHANGING THE ORIGINAL ARTWORK?
19. DOES THE IMAGE LOOK LIKE A REAL PHOTOGRAPH RATHER THAN A DIGITAL MOCKUP?
20. WOULD THE CUSTOMER RECOGNIZE THEIR IMAGE #1 PRODUCT AS **UNCHANGED**?

IF ANY ANSWER IS INCORRECT, **CORRECT IT BEFORE GENERATING THE FINAL RESULT.**

---

# FINAL OUTPUT REQUIREMENT

THE FINAL RESULT MUST LOOK AS THOUGH:

**THE EXACT CUSTOMER T-SHIRT FROM IMAGE #1 WAS PHYSICALLY PRODUCED USING THE REALISTIC GARMENT MATERIAL, SILHOUETTE, DRAPE, WRINKLES, CONSTRUCTION, PHOTOGRAPHY, AND DISPLAY PRESENTATION SHOWN IN IMAGE #2.**

IMAGE #1'S **DESIGN + COLOR + BRANDING + PRODUCT DETAILS MUST REMAIN UNCHANGED.**

IMAGE #2'S **DESIGN + COLOR + GRAPHICS + BRANDING MUST NOT APPEAR ANYWHERE IN THE FINAL RESULT.**

USE IMAGE #2 **ONLY AS THE PHYSICAL MOCKUP AND PRESENTATION REFERENCE.**

THE FINAL IMAGE MUST BE:

**PHOTOREALISTIC.
COMMERCIAL QUALITY.
CUSTOMER-READY.
TEXTURALLY REALISTIC.
PHYSICALLY BELIEVABLE.
100% FAITHFUL TO IMAGE #1'S PRODUCT DESIGN.
100% BASED ON IMAGE #2'S MOCKUP PRESENTATION STYLE.
ZERO UNAUTHORIZED DESIGN CHANGES.
ZERO AI ARTIFACTS.**`,
    refs: [],
    aspect: "square",
  },
  {
    id: 6,
    name: "Losses to Wins Tee",
    garment: "Tee",
    shot: "On body",
    summary: "Boxy white tee with three vertical collage panels.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 7,
    name: "Distressed Straight Jeans",
    garment: "Jeans",
    shot: "Flat lay",
    summary: "Vintage-wash straight jeans, heavy rips, raw hem.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 8,
    name: "Dark Luxury Tee",
    garment: "Tee",
    shot: "Studio",
    summary: "Placeholder. Black tee, hard light, luxury product shot.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 9,
    name: "Vintage Hoodie Hanger",
    garment: "Sweatshirt",
    shot: "Hanger",
    summary: "Placeholder. Washed hoodie on a hanger.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 10,
    name: "Clean Hoodie Flat",
    garment: "Sweatshirt",
    shot: "Flat lay",
    summary: "Placeholder. Neutral hoodie, top-down.",
    prompt: "",
    refs: [],
    aspect: "square",
  },
  {
    id: 11,
    name: "On-Body Hoodie",
    garment: "Sweatshirt",
    shot: "On body",
    summary: "Placeholder. Boxy hoodie, street editorial.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 12,
    name: "Dark Studio Hoodie",
    garment: "Sweatshirt",
    shot: "Studio",
    summary: "Placeholder. Black hoodie, studio sweep.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 13,
    name: "Black Tee Hanger",
    garment: "Tee",
    shot: "Hanger",
    summary: "Placeholder. Black graphic tee on a hanger.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 14,
    name: "Distressed On-Body Tee",
    garment: "Tee",
    shot: "On body",
    summary: "Placeholder. Cropped distressed tee, on body.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 15,
    name: "Washed Hoodie Flat",
    garment: "Sweatshirt",
    shot: "Flat lay",
    summary: "Placeholder. Faded hoodie, flat lay.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 16,
    name: "Clean Tee Hanger",
    garment: "Tee",
    shot: "Hanger",
    summary: "Placeholder. Crisp white tee on a hanger.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 17,
    name: "Dark On-Body Tee",
    garment: "Tee",
    shot: "On body",
    summary: "Placeholder. Black tee, night street light.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
  {
    id: 18,
    name: "Minimal Hoodie Hanger",
    garment: "Sweatshirt",
    shot: "Hanger",
    summary: "Placeholder. No-print hoodie, hanger.",
    prompt: "",
    refs: [],
    aspect: "portrait",
  },
];
/* looks:end */

export function getLook(id: number) {
  return LOOKS.find((look) => look.id === id) ?? null;
}

/** Append numbered image refs. #1… are mockups; following #s are this look's reference photos. */
export function withImageRefs(prompt: string, mockupCount: number, lookRefCount: number) {
  const refs: string[] = [];
  for (let i = 0; i < mockupCount; i += 1) {
    refs.push(`#${i + 1} user's mockup${mockupCount > 1 ? ` ${i + 1}` : ""}`);
  }
  for (let i = 0; i < lookRefCount; i += 1) {
    refs.push(`#${mockupCount + i + 1} look reference${lookRefCount > 1 ? ` ${i + 1}` : ""}`);
  }
  return `${prompt.trim()}\n\n${refs.join("\n")}`;
}
